from datetime import date
from io import BytesIO

from pypdf import PageObject, PdfReader, PdfWriter
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen.canvas import Canvas

from app.documents.aa912.models import AA912OpeningData

_PAGE_HEIGHT: float = float(A4[1])
_EXPECTED_TEMPLATE_PAGES = 5
_BOX_STEP = 14.4


class InvalidAA912Template(ValueError):
    pass


def render_aa912_opening(template_pdf: bytes, data: AA912OpeningData) -> bytes:
    """Overlay confirmed opening data onto the official AA9/12 PDF template."""
    source = PdfReader(BytesIO(template_pdf))
    if len(source.pages) != _EXPECTED_TEMPLATE_PAGES:
        raise InvalidAA912Template(
            f"expected {_EXPECTED_TEMPLATE_PAGES} template pages, got {len(source.pages)}"
        )

    writer = PdfWriter()
    for page_index, page in enumerate(source.pages):
        if page_index > 0:
            page.merge_page(_overlay(page_index, data))
        writer.add_page(page)

    output = BytesIO()
    writer.write(output)
    return output.getvalue()


def _overlay(page_index: int, data: AA912OpeningData) -> PageObject:
    buffer = BytesIO()
    pdf = Canvas(buffer, pagesize=A4)

    _page_header(pdf, page_index, data.fiscal_code)
    if page_index == 1:
        _opening_page(pdf, data)
    elif page_index == 4:
        _signature_page(pdf, data)

    pdf.save()
    buffer.seek(0)
    return PdfReader(buffer).pages[0]


def _page_header(pdf: Canvas, page_index: int, fiscal_code: str) -> None:
    x = 235.0 if page_index == 4 else 237.0
    top = 145.0 if page_index == 1 else 45.0
    _boxed(pdf, fiscal_code, x=x, top=top)
    _text_center(pdf, str(page_index), x=546.0, top=top)


def _opening_page(pdf: Canvas, data: AA912OpeningData) -> None:
    activity_address, activity_postal_code, activity_municipality, activity_province = (
        data.effective_activity_address
    )

    _mark(pdf, x=122.5, top=193.5)
    _boxed(pdf, _date(data.start_date), x=464.0, top=201.5)

    _text(pdf, f"{data.surname} {data.given_name}", x=120.0, top=334.0)
    _boxed(pdf, data.ateco_code, x=160.5, top=420.8)
    _text(pdf, data.activity_description, x=258.0, top=420.5, size=8.0)
    _address(pdf, activity_address, activity_postal_code, activity_municipality, activity_province)

    if data.accounting_records_at_activity_address:
        _mark(pdf, x=556.5, top=477.8)

    # AA9/12 code 2 = regime forfettario for the supported opening path.
    _text_center(pdf, "2", x=323.5, top=548.0)

    _boxed(pdf, data.fiscal_code, x=162.0, top=626.0)
    _text(pdf, data.surname, x=350.0, top=630.0)
    _text(pdf, data.given_name, x=460.0, top=630.0)
    _boxed(pdf, _date(data.birth_date), x=120.0, top=650.8)
    _text(pdf, data.birth_municipality, x=237.0, top=650.5)
    _boxed(pdf, data.birth_province, x=548.0, top=650.8)

    _text(pdf, data.residence_address, x=120.0, top=677.5)
    if data.accounting_records_at_activity_address and data.activity_at_residence:
        _mark(pdf, x=556.5, top=677.3)
    _boxed(pdf, data.residence_postal_code, x=120.0, top=701.8)
    _text(pdf, data.residence_municipality, x=193.0, top=701.5)
    _boxed(pdf, data.residence_province, x=548.0, top=701.8)


def _address(pdf: Canvas, address: str, postal_code: str, municipality: str, province: str) -> None:
    _text(pdf, address, x=120.0, top=482.0)
    _boxed(pdf, postal_code, x=120.0, top=496.8)
    _text(pdf, municipality, x=193.0, top=496.5)
    _boxed(pdf, province, x=548.0, top=496.8)


def _signature_page(pdf: Canvas, data: AA912OpeningData) -> None:
    for x in (290.0, 312.0, 334.0):
        _mark(pdf, x=x, top=92.8)
    _text_center(pdf, "4", x=550.0, top=93.0)

    if data.declaration_date is not None:
        _boxed(pdf, _date(data.declaration_date), x=137.0, top=133.8, step=10.8)
    _boxed(pdf, data.fiscal_code, x=344.0, top=133.8)
    # Signature is intentionally never generated by software.


def _date(value: date) -> str:
    return value.strftime("%d%m%Y")


def _boxed(
    pdf: Canvas,
    value: str,
    *,
    x: float,
    top: float,
    step: float = _BOX_STEP,
    size: float = 8.0,
) -> None:
    text = value.upper().replace(".", "").replace("/", "").replace(" ", "")
    pdf.setFont("Helvetica", size)
    for index, character in enumerate(text):
        pdf.drawCentredString(x + index * step, _y(top), character)


def _text(pdf: Canvas, value: str, *, x: float, top: float, size: float = 8.5) -> None:
    pdf.setFont("Helvetica", size)
    pdf.drawString(x, _y(top), value.upper())


def _text_center(pdf: Canvas, value: str, *, x: float, top: float, size: float = 8.0) -> None:
    pdf.setFont("Helvetica", size)
    pdf.drawCentredString(x, _y(top), value)


def _mark(pdf: Canvas, *, x: float, top: float) -> None:
    pdf.setFont("Helvetica-Bold", 8.0)
    pdf.drawCentredString(x, _y(top), "X")


def _y(top: float) -> float:
    return _PAGE_HEIGHT - top
